# MyDistro default kitty config.
font_family      JetBrainsMono Nerd Font
font_size        11.0

background       #1a1b26
foreground       #c0caf5
cursor           #1793d0

color0  #15161e
color8  #414868
color1  #f7768e
color9  #f7768e
color2  #9ece6a
color10 #9ece6a
color3  #e0af68
color11 #e0af68
color4  #7aa2f7
color12 #7aa2f7
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #7dcfff
color7  #a9b1d6
color15 #c0caf5

window_padding_width 8
confirm_os_window_close 0
